# This config is used to run the Cornerstone 2026 model schema on the 2025 USA data with waste disaggregation enabled.

#####
# Model base settings
#####

#####
# Data selection
#####

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True
implement_waste_disaggregation: True
eeio_waste_disaggregation:
  use_weights_file: "extract/disaggregation/WasteDisaggregationDetail2017_Use.csv"
  make_weights_file: "extract/disaggregation/WasteDisaggregationDetail2017_Make.csv"
  year: 2017
  source_name: "WasteDisaggregationDetail2017"

#####
# Bugfix
#####
