# This config is used to run the Cornerstone 2026 model schema on the 2025 USA data.

#####
# Model base settings
#####

#####
# Data selection
#####

#####
# Methodology selection
#####
use_cornerstone_2026_model_schema: True


#####
# Bugfix
#####