#####
# Model base settings
#####
model_base_year: 2024

#####
# Data selection
#####
usa_io_data_year: 2024
usa_ghg_data_year: 2024

#####
# Methodology selection
#####
ipcc_ar_version: "AR6"


#####
# Bugfix
#####