model_base_year: 2023
usa_ghg_data_year: 2023
use_cornerstone_2026_model_schema: True
implement_waste_disaggregation: True
eeio_waste_disaggregation:
  use_weights_file: "extract/disaggregation/Use.csv"
  make_weights_file: "extract/disaggregation/Make.csv"
  year: "not_an_integer"
  source_name: "Test"
